name: deploy-container

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Set Environment Variable
        run: echo "NODE_ENV=production" >> $GITHUB_ENV

      - name: Generate Deployment Package
        run: zip -r nodejs-app-build.zip . -x "node_modules/*" ".git/*" "*.log"

      - name: Deploy to Elastic Beanstalk
        uses: aws-actions/beanstalk-deploy@v1
        with:
          application-name: 'TaxQue'
          environment-name: 'TaxQue-env'
          version-label: ${{ github.sha }}
          region: 'us-east-2'
          bucket-name: ${{ secrets.S3_BUCKET_NAME }}
          bucket-key: nodejs-app-build.zip
